### ISSUE TITLE
No models found - Little Mermaid 2

### ISSUE THREAD

**Issue by spamzilla** [rickomax/psxprev#183]
Upon scanning, I found that Disney's the Little Mermaid 2 has around 150 animations but no models! This seems to be very counterintuitive.

**Comment by spamzilla** [comment]
The results I'm getting from 0.9.9.2 are much improved. Lots of models in this game. A lot of map geometry but also stuff like a mermaid, fish, a trident, people, etc.

**Comment by trigger-segfault** [comment]
Oh that's good. I should have recognized that Blitz Games developed this, since I saw Ariel's model as leftover data in Chicken Run.

Considering the format Ariel's model is in already supports animations, it's likely those original 150 animations you found were false positives.

Thanks for the follow up. :)
