### ISSUE TITLE
Intelligent Qube Final - HMD files not reading

### ISSUE THREAD

**Issue by LadyLeia001** [rickomax/psxprev#29]
**Intelligent Qube Final** uses the HMD format to store models but the thing is they are external files with the extension ".HMD" only "BALL.HMD" and "PR.HMD" read though the format is the same for all the ".HMD" files. Also if you pack them up and run PsxPrev again you get another model of the dog from the game. I'm unsure if its a mistake with how your reading the HMD files or the way it scans for them. Anyways thanks for making this neat little took though its clearly far from perfect for some games, i hope this problem resolves itself soon.

Also this is kinda unrelated but do you know any other tools for dealing with the HMD model format? Im working on a project that ill be converting from this file a lot.

oh and i attached these files for the models (as well as the animation format, unsure if it helps at all) so you can see if you can recreate the problem I'm having.
[MODELS.zip](https://github.com/rickomax/psxprev/files/4825151/MODELS.zip)

**Comment by rickomax** [comment]
HMD file format is only partially implemented in PSXPREV, as the HMD specification is a big extensive, I still need to finish it.
I'm not aware of any other tool that can deal, at least partially, with HMD files.

**Comment by trigger-segfault** [comment]
All your submitted models load now as of #49 being pushed. The only issue (that I'm not sure if it's supposed to be like that) is that the tie on `EL.HMD` doesn't draw on the upper half of his shirt.

The reason why the dog `SP.HMD` loaded when all the files were packed up was likely due to it originally trying to read outside the file bounds, but it was in the bounds of another HMD file while packed.

![image](https://github.com/rickomax/psxprev/assets/9752430/b97f13eb-2db3-4cd3-8169-7469b7363862)
