### ISSUE TITLE
Lego Rock Raiders HMD files all load as Croc Models with 0 polygons

### ISSUE THREAD

**Issue by RingtailRaider** [rickomax/psxprev#47]
I'm trying to use this tool to view files from the game Lego Rock Raiders on PS1, but it has a weird issue where almost all of the HMD files are detected as "Croc Model" rather than HMD, and load with 0 polygons. They seem to be a weird format that contains models, textures, and animations all in one file, so that might be part of the issue since this program seems to assume HMD files will use separate TIM/TMD files for textures. Only 2 HMD files in the entire game (out of 51 total) are properly detected as HMD models. I can supply any of the game's files if needed.

**Comment by trigger-segfault** [comment]
All models correctly load as HMD as of #49 being pushed. There's some minor issues that need to be fixed in the renderer, but the models themselves are all good (aside from the Support Station `barracks.hmd` being inexplicably raised a bit). 👍 

Edit: Apparently the support station is raised like that in-game too. It wouldn't be if they had told the model to animate, but whatever.

![image](https://github.com/rickomax/psxprev/assets/9752430/78aa534b-1cfd-46a4-a39f-7bbbcbbe4388)
